### ISSUE TITLE
Format string breaks nick coloring

### ISSUE THREAD

**Issue by scottjad** [jorgenschaefer/circe#107]
Nick coloring stops working if a format string is set on the nick (and changes the nick). Ideally nick coloring would continue even if the nick were truncated..

Both of these disrupt nick coloring unless the nick is 8 characters long:
(setq circe-format-say "{nick:8s} : {body}")
(setq circe-format-say "{nick:8.8s} : {body}")

**Comment by TaylanUB** [comment]
Currently the function `circe-color-nicks`, which is in `lui-pre-output-hook`, uses the actual nick found in the lui output line (as determined by the `nick` text property) to do a hash table lookup, which of course fails when the nick has been modified for display purposes.  Maybe the real nick of the sender of the line can be acquired from somewhere.  Help by @jorgenschaefer welcome.

**Comment by jorgenschaefer** [comment]
The `:nick` property of a message with those format strings is the nick, excluding the spaces, so that's not the problem.

**Comment by TaylanUB** [comment]
Jorgen Schäfer <notifications@github.com> writes:

> The :nick property of a message with those format strings is the nick,
> excluding the spaces, so that's not the problem.

I'm not sure I understand.  Isn't the formatting applied before the
pre-output hook (`circe-color-nicks') is called?  So the pre-output hook
only sees the formatted nick, the original one having disappeared, so to
say.

**Comment by jorgenschaefer** [comment]
I just set my `circe-format-say` to `<{nick:16s}> {body}`. The text in the buffer then was:

```
<    friesenpeter> ecraven: I just switched a window to display the     [10:35]
    speedbar buffer, it shows up
```

The `lui-keywords` text property had the following value:

```
(:mynick "forcer"
 :target "#emacs"
 :nick #("friesenpeter" 0 12 (face circe-originator-face))
 :body "ecraven: I just switched a window to display the speedbar buffer, it shows up")
```

I.e. the `:nick` property does not contain any spaces.

**Comment by TaylanUB** [comment]
Jorgen Schäfer <notifications@github.com> writes:

> The lui-keywords text property [...]

Neat, I wasn't aware of that property. :-)

Patch coming soon.
