### ISSUE TITLE
"Process killed" on C-c C-r after recent update

### ISSUE THREAD

**Issue by david-christiansen** [jorgenschaefer/circe#113]
After a recent Circe update, when I try to reconnect to my bouncer (bip, running over TLS), I get the message "Process SERVERNAME killed" and nothing happens. If I kill all the Circe buffers and try connecting from scratch, then it works.

**Comment by jorgenschaefer** [comment]
Thank you for the report!

In your `*Messages*` buffer, you should see messages like "Opening TLS connection …" – could you post them from both when it does not work and when it works?

**Comment by david-christiansen** [comment]
Sorry to be so slow responding - I'm out traveling.
Here's from when it works:
```
Opening TLS connection to `SERVER'...
Opening TLS connection with `gnutls-cli --insecure -p PORT SERVER'... failed
Opening TLS connection with `gnutls-cli --insecure -p PORT SERVER --protocols ssl3'... failed
Opening TLS connection with `openssl s_client -connect SERVER:PORT -no_ssl2 -ign_eof'... done
```

And here's from when it doesn't on `C-c C-r` in the SERVER buffer:
```
Opening TLS connection to `SERVER'...
Opening TLS connection with `openssl s_client -connect SERVER:PORT -no_ssl2 -ign_eof'... done
```
I've redacted my actual server and port in the above. If I kill the server buffer and re-connect, it does what we see in the first one.

This "process killed" message is something I've only started experiencing after a recent update from MELPA.

Thanks!

**Comment by jorgenschaefer** [comment]
Strange. That looks like it is doing The Right Thing.

@defanor, any idea what might be going on here, or how to debug this further?

**Comment by david-christiansen** [comment]
This is a note for myself based on an IRC conversation with @defanor: when the error is happening, post the result of `(get-buffer-process (current-buffer))` as well as the log from my Bip server to this issue.

I'll do it when I get home.

**Comment by defanor** [comment]
Meantime: failed to reproduce with both bip 0.8.8 and 0.8.9, as well as with znc.
By the way, if you try `C-c C-r` after that "process killed" message, it's still the same ("done", and then another "process killed" message), right?

**Comment by defanor** [comment]
More things to try in the server buffer after that error, in case if other tests won't reveal its origin: `(circe-tls-buffer-occupied-p (current-buffer))` and `(buffer-live-p (current-buffer))`.

**Comment by jorgenschaefer** [comment]
If you ever get `(buffer-live-p (current-buffer))` to return `nil`, we get to file a most interesting bug report on Emacs! :-D

**Comment by defanor** [comment]
Ouch, indeed. Okay, we could skip that one.

**Comment by david-christiansen** [comment]
Here's some more stuff, from the server buffer when I have the error:
```
M-: (get-process-buffer (current-buffer)) RET
#<process box.davidchristiansen.dk>
M-: (process-live-p (get-buffer-process (current-buffer)))
(run open listen connect stop)
M-: (circe-tls-buffer-occupied-p (current-buffer))
nil
```

When I repeat my `C-c C-r`, I get a new password prompt from Bip above the input prompt and a new "Process SERVER killed" below the prompt.

**Comment by defanor** [comment]
Apparently the process died between those calls.

As long as there's some password prompt (where it comes from, btw?), could you try to load Circe alone into `emacs -Q`, with minimal config, and try it again -- to be sure that other modes don't interfere? Also would be nice to check `(process-sentinel (get-buffer-process (current-buffer)))` right after the reconnect/error: it seems that the sentinel is getting lost somehow, which would explain that behaviour, but it should always be there.

**Comment by defanor** [comment]
Probably found another bug, though might be related: when sending wrong credentials to bip, it seems that it drops the connection, and then I'm getting `eq: Wrong type argument: stringp, nil`.

**Comment by defanor** [comment]
The error I've ran into appears to be in `circe-server-filter-function`, which fails on strings like `read:errno=0`.

**Comment by jorgenschaefer** [comment]
Well, that is not a valid IRC protocol message. I guess the error could be more precise, but why is that being sent to that function?

**Comment by defanor** [comment]
So, another question to @david-christiansen: can't it be that you are sending some invalid credentials on reconnect? It won't explain how the sentinel is getting lost, but would explain why this problem occurs.

**Comment by defanor** [comment]
@jorgenschaefer: That's simply what the openssl process outputs. Not sure whether it comes from openssl or from bip.

**Comment by jorgenschaefer** [comment]
I'd be really curious how this works with current Circe master. The whole connection functions, IRC parser, pretty much everything involved here has been rewritten. :-)

**Comment by david-christiansen** [comment]
Sorry for being slow here.

By default, my bouncer (bip) will send a little prompt asking you to enter `/quote pass username:password:network` when you connect without providing credentials:
```
-Server Notice- You should type /QUOTE PASS
    your_username:your_password:your_connection_name
```
Alternatively, that string can be provided as a password directly upon connection. Before, I was doing the former thing.

I later switched to the latter after figuring out Emacs's gnome-keyring integration well enough to save my password somewhere other than the configuration files. This seemed to make the issue go away. While I was playing with it, Circe was updated with the updates you describe.

I've gotten back to test with my old config, and everything works as it should.

Thanks so much!

**Comment by david-christiansen** [comment]
Just to clarify: both my old and new config work with the latest master.
