### ISSUE TITLE
pop to buffer for auto joined channels

### ISSUE THREAD

**Issue by jaor** [jorgenschaefer/circe#114]
Since the latest release (more or less, i'm using the MELPA version), when i connect (or reconnect) to the server and channels are auto-joined, each new channel buffer pops up, as if `circe-new-buffer-behavior` were `'display` and `circe-new-buffer-behavior-ignore-auto-joins` were `nil`, but i've customized those variables to `'ignore` and `t` respectively.  Am i missing some other setting?

**Comment by jorgenschaefer** [comment]
Thanks for the report! Looks like there was a spurious use of `circe-command-JOIN` in lisp code. The commit above should fix this. If it does not fix the problem, please do not hesitate to re-open this issue or file a new one!

**Comment by jaor** [comment]
Thanks for the quick fix! The new version does indeed solve the problem.
