### ISSUE TITLE
Integration w/ Projectile: Circe buffers should not belong to projects

### ISSUE THREAD

**Issue by jinnovation** [jorgenschaefer/circe#134]
Currently, connecting to a server/channel/etc while inside a window open on a
buffer that's dedicated to another project under
[Projectile](http://batsov.com/projectile/) causes those Circe buffers to become
associated with that project.

This seems counter-intuitive, given that I imagine that the majority of users'
IRC usage is "general," i.e. independent of whatever project they may or may not
be working on.

However, this project association becomes problematic when running a command
such as `projectile-kill-buffers`, at which point Emacs will attempt to also
attempt to kill all Circe buffers created from within that project.

I propose to dissasociate Circe buffers completely from Projectile such that no
Circe buffers show up as "belonging" to a given project.

**Comment by wasamasa** [comment]
Interesting, I assumed Projectile to associate buffers to a project by their file location up to a VCS- or Projectile-specific file which would for instance put all files in a Git repository in one project.

**Comment by jinnovation** [comment]
This could potentially be a bug on the Projectile side, but I nevertheless think that it wouldn't hurt to investigate things from both ends so that we *can* definitively pin down the origin.

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report!
`projectile-kill-buffers` considers all buffers to belong to a project if they have a `default-directory` under the project root. Emacs buffers retain `default-directory` from the buffer they were created in, so if you connect to an IRC server from a buffer in `~/projects/foo`, Circe buffers will all retain that `default-directory`, and Projectile will consider them all part of the project. All of this seems pretty sensible (as far as standard weird Emacs semantics go), so I do not think there is a bug per se.

The official solution from projectile is to add `circe-.*-mode` to `projectile-globally-ignored-modes`. This will prevent Projectile from considering any of the Circe buffers as project buffers.

As for Circe, I actually do think Circe should not inherit `default-directory` from the buffer it was started in, for pretty much the same reasons as mentioned in this issue: Circe is usually meant to be global, not specific to some directory.

So I would think Circe should add a `circe-default-directory` variable which Circe will set `default-directory` to when it starts.

How does that sound?

**Comment by jinnovation** [comment]
That sounds like a solid idea to me. Adding `circe-*-mode` to `projectile-globally-ignored-modes` is a solution, but having a variable like `circe-default-directory` would, I believe, be a much less hacky solution, and one that'd preemptively prevent other issues like this from potentially popping up in the future.

At the end of the day, like you said, Circe is definitely meant to be global, and as such, having its own `default-directory` independent of whichever directory it was started in, like you suggested, makes a lot of sense.
