### ISSUE TITLE
/whois name name doesn't work

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/circe#142]
`/whois name` gives me regular whois information. Trying out the extended variant by passing the name twice with `/whois name name` (which would give me idle times) gives me:

```
*** No such nick: name
*** name
```

I'm pretty sure this used to work in a prior version of Circe.

**Comment by jorgenschaefer** [comment]
Yup, `circe-command-WHOIS` needs to parse multiple arguments. Thanks for catching this!

**Comment by wasamasa** [comment]
Here's my first attempt at this:

```elisp
(defun circe-command-WHOIS (whom)
  "Request WHOIS information about WHOM."
  (interactive "sWhois: ")
  (let* ((whom-server-name (split-string whom))
         (whom (car whom-server-name))
         (server-or-name (cadr whom-server-name)))
    (irc-send-WHOIS (circe-server-process) whom server-or-name)))

(defun irc-send-WHOIS (conn target server-or-name)
  "Retrieve current whois information on TARGET."
  (if server-or-name
      (irc-send-command conn "WHOIS" target server-or-name)
    (irc-send-command conn "WHOIS" target)))
```

**Comment by jorgenschaefer** [comment]
That looks reasonable, in as far as the current command handling is reasonable …

**Comment by wasamasa** [comment]
Good, I'll push that change as is then.

**Comment by jorgenschaefer** [comment]
Could you add a test at least for `irc-send-WHOIS`, please? :-)

**Comment by wasamasa** [comment]
Done.

**Comment by jorgenschaefer** [comment]
Thank you! :-)
