### ISSUE TITLE
Unicode in nicks

### ISSUE THREAD

**Issue by defanor** [jorgenschaefer/circe#144]
Not sure if it's caused by Circe, but something strange is going on with unicode nicks:
- They are fine in the "names" list, as well as in whois messages; it's also fine if they are mentioned a regular (PRIVMSG) message.
- In a message buffer, when there's a message from somebody with such a nick, I'm getting them shown as sequences of escaped character codes: e.g., "К" (CYRILLIC CAPITAL LETTER KA) becomes "\320\232", which could be copied, and then pasted as "К" outside of emacs, but still "\320\232" in emacs; though it's "К" in emacs if copied from emacs, pasted in FF, copied from FF, pasted in emacs, so maybe it has something to do with text properties, like `circe-originator-face` (color-nicks are not enabled, btw).
- When checking `describe-text-properties`, and then `lui-keywords` or `lui-raw-text`, such nicks (`:nick`) are of the form `#("\320\232..." 0 9 (face circe-originator-face))` there, while messages (`:body`) are readable strings.
- If ascii chars are mixed with unicode chars, I still can see ascii chars.
- When such a nick was changed (to all-ascii), I haven't seen a message about it.
- Maybe not related, but when I've added a unicode character into my nick, lagmon wasn't able to ping me (never tried it before, so maybe it's not new).

Circe 20150423.1452, Emacs 24.4.3. Worked fine before.

**Comment by defanor** [comment]
They are also shown in that form ("\320\232...") in join messages, and haven't seen any quit messages with those nicks.

**Comment by defanor** [comment]
One more thing: in whois messages, such nicks are not highlighted, while others are.

**Comment by jorgenschaefer** [comment]
Thanks for the report. Probably a side effect of the new irc.el, which likely does not decode nicks as well as bodies of messages.

**Comment by jorgenschaefer** [comment]
The 9bd8547 update should fix this problem. Please do report if you see this behavior again with that code!
