### ISSUE TITLE
Use define-derived-mode for all modes

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/circe#150]
The resulting hiearchy should look something like this:

```
lui-mode
`- circe-mode
   |- circe-server-mode
   `- circe-chat-mode
    |- circe-channel-mode
    `- circe-query-mode
```

See http://www.gnu.org/software/emacs/manual/html_node/elisp/Example-Major-Modes for examples on how to define major modes in a modern Emacs.

**Comment by wasamasa** [comment]
Hmm, isn't that taken care of already?  At least that's what the sources of `circe.el` are suggesting with exactly the same infographic and the usage of `define-derived-mode` in it.

**Comment by jorgenschaefer** [comment]
Oh, indeed! Thanks :-D
