### ISSUE TITLE
Remove message options

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/circe#152]
I looked at message options, and I saw that it was terrible.

Not sure what to replace it with, but it can't stay this way. Seriously.

- irc.el needs an ignore feature for replies
- circe.el needs a fool feature for displaying

**Comment by wasamasa** [comment]
Sounds like a breaking change though, considering that this feature can be used to gray out bot text and generally highlight text.

**Comment by jorgenschaefer** [comment]
We broke Circe left and right the last few weeks, so why not this one :-D

Just need to make sure we can keep actually desired features. I'd appreciate it if people added their own use cases for this feature. (Your use cases, or use cases you are positive someone actually has out there, not potential or possible use cases :-D)

My two use cases would be:

- As a user, I would like to specify nick!user@host patterns to ignore in order to avoid flooding the IRC server with automatic responses (mainly CTCP)
- As a user, I would like to specify nick!user@host patterns to hide in order to be able to read an IRC channel without messages from annoying users, but still able to show their messages in case they're part of another discussion.

**Comment by wasamasa** [comment]
Here's some [current](https://github.com/jorgenschaefer/circe/wiki/Configuration#gray-out-bot-text) [wiki](https://github.com/jorgenschaefer/circe/wiki/Configuration#chanserv-welcome-notices-in-appropriate-channel-buffer) [examples](https://github.com/jorgenschaefer/circe/wiki/Configuration#adding-message-options-to-the-rerouted-display).

Currently I'm using the feature for working around the weaknesses of the current highlighting system, see [my init file](https://github.com/wasamasa/dotemacs/blob/master/init.org#hacks).  It sort of solves #72, come to think of it.

**Comment by jorgenschaefer** [comment]
Interesting, thanks!

What does `my-x-urgency-hint` do there?

**Comment by wasamasa** [comment]
It sets a X urgency hint for the Emacs frame which marks the i3 workspace it's on in red. This hint is then cleared when viewing that workspace.

**Comment by jorgenschaefer** [comment]
Interesting!

- **ChanServ welcome notices in appropriate channel buffer** and **Adding message-options to the rerouted display:** This should define a display handler that just calls the original display handler
- **Gray Out Bot Text:** This should have a direct interface to set the "base face" for messages based on sender or body text
- **init.org:**
  - The `my-x-urgency-hint` feature needs a "we were highlighted!" hook (see the original request in #72)
  - The other part needs a list of other nicks we own as an addition to the nick highlighting

Anything I missed?

**Comment by jorgenschaefer** [comment]
This should likely tie in with #28 (Ignore rewrite) to add more complex matching for messages and more options for message display than show/don't show.

Also, message display should always use configurable formats. This might help here. Hm.

**Comment by wasamasa** [comment]
Nothing new showing up on Github's search for the variable, so I hope that's all.

**Comment by wasamasa** [comment]
I guess this can be marked closed now that https://github.com/jorgenschaefer/circe/commit/d8cd63516503da6bde216c737d4bf46fad341109 happened?

**Comment by jorgenschaefer** [comment]
Ok, the missing features I mentioned above now have their own issues, so this can be closed indeed. Thank you for noticing it!
