### ISSUE TITLE
Customize show-paren-mode for IRC

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/circe#160]
As a user, I want to have matching parens highlighted only within the input area, certainly not in the rest of the IRC window, so I can write balanced expressions, but not get weird matches thanks to smileys.

Circe should likely set a custom `show-paren-data-function` that uses `show-paren--default` but checks its values for whether they are within the input line.

**Comment by wasamasa** [comment]
The description of this feature reminds me of flyspell support in lui.  Would it make sense to implement it in a similiar way and in the same library?

**Comment by jorgenschaefer** [comment]
Very good idea, this should be a lui feature indeed!
