### ISSUE TITLE
:reduce-lurker-spam

### ISSUE THREAD

**Issue by defanor** [jorgenschaefer/circe#167]
Failing to set `reduce-lurker-spam` per-server. Here's my `circe-network-options`:
```elisp
(setq circe-network-options
      `(("Bitlbee"
         :nick ,bitlbee-nickname
         :realname ,bitlbee-nickname
         :user ,bitlbee-nickname
         :nickserv-password ,bitlbee-password)
        ("freenode-znc"
         :nick ,freenode-nickname
         :realname ,freenode-nickname
         :user ,freenode-nickname
         :pass ,znc-freenode-password
         :reduce-lurker-spam t)))
```
With that, getting `circe-reduce-lurker-spam` set to `t` in the server buffer, but to `nil` in channel buffers.

Circe version 20150519.1115, Emacs 24.5.1.

**Comment by jorgenschaefer** [comment]
Thanks for the report. I guess chat modes should copy that setting. Hm.

(We need per-channel settings in the server config :-D)

**Comment by jorgenschaefer** [comment]
This is tricky, actually.

There's a global value, and by default, this is the only one.

If you set it with network or server options like above, you create a server-local variable. But how should the channel buffer know whether to use the global value or the server-local one?

The following should work to fix this temporarily, but a general solution is tricky:

```Lisp
(add-hook 'circe-channel-mode-hook (lambda () (setq-local circe-reduce-lurker-spam (with-circe-server-buffer circe-reduce-lurker-spam))))
```

**Comment by defanor** [comment]
Thanks, will try that.
