### ISSUE TITLE
/join #foo,#bar is funny

### ISSUE THREAD

**Issue by TaylanUB** [jorgenschaefer/circe#168]
When I do `/join #foo,#bar`, Circe thinks I'm trying to join the channel `foo,#bar` and creates a buffer for it, then the IRC server does something smart and joins me to `#foo` and `#bar`, for which buffers get created too.

Some related problems ensue because of messed-up meta-data on our side, but it's probably not worth enumerating these; parsing a whitespace and/or comma separated join list and doing the right thing on our side without ever passing the server a comma-separated channel list would probably solve the issue neatly.

**Comment by jorgenschaefer** [comment]
Indeed, `/JOIN` should split channel names by comma …

Not by whitespace, though. `/join #foo bar` joins `#foo` with the password `bar`. (Yeah, IRC has channel keys which no one uses but we have to support them anyhow :-D)
