### ISSUE TITLE
Double connections with TLS and lagmon

### ISSUE THREAD

**Issue by defanor** [jorgenschaefer/circe#169]
On a network disconnect, with lagmon enabled, this happens:
```
*** Disconnected
*** Connecting...
*** Connecting...
```
It leads to two connections, both created at the same minute, and both providing messages to buffers (so all the messages are doubled). Killing those processes and reconnecting (`C-c C-r`) helps, but until the next disconnect.

Circe 20150529.108, Emacs 24.5.1. Also happened on some older Circe (a few weeks old) and Emacs 24.4.3.

**Comment by jorgenschaefer** [comment]
Hrmph. This should not happen! :-) Thanks for the report.

I suspect there's a problem with lagmon, but I am not sure what or why `circe-reconnect` would not be idempotent. Something to investigate.

**Comment by defanor** [comment]
It didn't happen for a few days now, with the same Circe and Emacs versions, and even the same Circe instance running. I'm also not getting a "*** Disconnected" message in channel buffers anymore: now there's only a single "*** Connecting..." message after network disconnect.

**Comment by defanor** [comment]
Now it happened again; this time I didn't wait for lagmon to reconnect, but reconnected manually when the lag started to grow. The only change I could think of, comparing to the time when it worked fine, is that I've restarted another Circe instance yesterday, in the same Emacs instance.

**Comment by jorgenschaefer** [comment]
The problem appears to be that the `conn.disconnected` signal causes another connection attempt, while we're already connecting.
