### ISSUE TITLE
/part throws an error

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/circe#171]
[Backtrace](http://ix.io/j0Q).

**Comment by jorgenschaefer** [comment]
Hm. Thanks for the report. Multiple errors here.

- The user parts a channel, after which the channel is not available from irc.el anymore. Circe should be able to handle that.
- It shouldn't call this in the first place, as the user left and if "we" leave, we do not need to check if we're a lurker.

**Comment by jorgenschaefer** [comment]
This should be fixed in the latest git version. Can you verify that?

**Comment by wasamasa** [comment]
Yup, that is fixed. I've noticed another oddity though, after using `/part` successfully, killing the buffer and confirming that I wish to quit, I get a "*** You are not on #freenode" notice in the Circe buffer I've switched to.

**Comment by jorgenschaefer** [comment]
Well, killing the buffer sends a `PART` message, which is what you get the error for … as tracking what channels you are on is somewhat unreliable on IRC, the options we have are to either possibly not send a `PART` message when we should, or send a `PART` message when we shouldn't. We're currently doing the latter. Do you think we should go for the former?

**Comment by wasamasa** [comment]
No, I think I'll just kill buffers if I don't want them to linger around, maybe play around with `kill-buffer-hook`.
