### ISSUE TITLE
Reconnecting to all servers

### ISSUE THREAD

**Issue by galderz** [jorgenschaefer/circe#172]
Is it possible to reconnect to all connected servers? I have configured 2 servers, and but if I execute `circe-reconnect` (or `C-c C-r`), it only seems to reconnect the chat rooms of one of the servers. Which server is selected depends on which server the channel in the buffer is linked to.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! There's a `M-: (circe-reconnect-all)` function which for no apparent reason is not a command to be called with `M-x`. Does this fix your use case? :-)

**Comment by galderz** [comment]
Hmmm, it didn't fully work. Seems like it was fine with Freenode, but another of the servers did not connect. I need to try more times. I'll close for now and reopen if needed.
