### ISSUE TITLE
`Selecting deleted buffer` errors

### ISSUE THREAD

**Issue by galderz** [jorgenschaefer/circe#173]
I'm sometimes having issues with executing circe commands or IRC commands, I get errors like `Selecting deleted buffer` :|. 

For example, the other day I did `/join #...`, and then I closed the buffer with `C-x C-k` at which point it asked me if I wanted to leave that specific channel. Then I couldn't do anything in the any of the other irc channels. I kept getting `Selecting deleted buffer` message.

**Comment by jorgenschaefer** [comment]
Thanks for the report. I assume you're using the development version?

**Comment by galderz** [comment]
Got it from melpa, version: `20150529.108`

**Comment by jorgenschaefer** [comment]
MELPA always always means "development version, unstable, careful, if it breaks you can keep both pieces" :-) In this case, it is indeed the development version of Circe, which is currently undergoing some major rewrite of certain internals – these bug reports are greatly appreciated, thank you!

**Comment by jorgenschaefer** [comment]
Ok. I just tried your reproduction steps and did not receive such an error – could you run `M-x toggle-debug-on-error` and see if you can get a backtrace? That would be greatly appreciated!

**Comment by galderz** [comment]
Hmmm, wasn't aware of MELPA giving snapshots. Is it possible to configure MELPA to only provide released versions? I've tried again and can't replicate it now :(

I'll keep an eye in case it happens again. Shall I enable `M-x toggle-debug-on-error` continously now? Or shall I enable once the issue appears once again?

**Comment by wasamasa** [comment]
One doesn't simply configure MELPA.

More seriously, if you wish for released versions from MELPA, try [MELPA Stable](http://stable.melpa.org/). Alternatively, you could be using [Quelpa](https://github.com/quelpa/quelpa) to build packages locally with the full power of MELPA recipes.

**Comment by jorgenschaefer** [comment]
> Hmmm, wasn't aware of MELPA giving snapshots.

Yes, they make it rather difficult to see this. It's a continuing problem, as authors of software have to deal with the fallout of them distributing snapshots all the time, so they create more work for others.

> Is it possible to configure MELPA to only provide released versions?

The next release of Emacs will make it possible to use MELPA as a fall-back archive only, but until then, your best bet is to use MELPA stable, not MELPA. You will have to re-install packages by hand, though, as MELPA overrides version numbers which means no other package archive provides a way to upgrade from those packages.

(MELPA stable has other problems, sadly.)

> I'll keep an eye in case it happens again. Shall I enable M-x toggle-debug-on-error continously now? Or shall I enable once the issue appears once again?

You can keep it active if you like. It will pop up a backtrace every time there is an error anywhere, which you can get rid of with `q` – if this is too annoying, you can disable it and enable it only when the problems come back.

Sorry I can't be of more help in debugging this problem :-(

**Comment by wasamasa** [comment]
@galderz You could alternatively take a look at your ELPA directory (located in `~/.emacs.d/elpa`) and see whether there are other snapshots of Circe and its dependencies still present, you could then move the newer ones somewhere else and load a new Emacs instance to see whether you can reproduce the issue with the older ones.

**Comment by galderz** [comment]
Hmmmm, Ok. I'll close this for now. I'll try to remove the melpa version and install one of the released versions. I'll reopen if it happens then.
