### ISSUE TITLE
configuration example for ssl

### ISSUE THREAD

**Issue by gour** [jorgenschaefer/circe#174]
Hello,

it would be nice to have simple configuration example for those using authorization with client SSL certificate, something like:

```
(setq circe-network-options
      `(("Freenode"
         :nick "forcer"
         :channels ("#emacs" "#emacs-circe")
         :host "chat.freenode.net"
         :service 7070
         :tls t )))

```

It would save me and hopefully others some time. ;)

**Comment by jorgenschaefer** [comment]
Good idea, thank you for bringing it up!

**Comment by jorgenschaefer** [comment]
Example added with 62a7abb. Also, as of a79601, TLS is the default for Freenode.
