### ISSUE TITLE
What has circe-chat-input been changed to?

### ISSUE THREAD

**Issue by kozross** [jorgenschaefer/circe#185]
I had a bunch of custom commands defined using ``circe-chat-input``, but now these don't work anymore as that command is no longer mapped to anything. What should I use instead?

**Comment by jorgenschaefer** [comment]
The function was renamed to `circe--input`, as I thought it would be rather internal and not used by third-party extensions – out of curiosity, what are you using it for? If it's generally useful, it should have a public name.

**Comment by kozross** [comment]
jorgenschaefer: I'm using this to mostly write commands similar to this one:

```
(defun circe-command-PHP (&optional ignored)
  (circe-chat-input "Why PHP is bad: http://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/"))
```

Although this is only a simple example - I have more complex ones out there.

**Comment by jorgenschaefer** [comment]
Interesting! Do these function calls use the command expansion – like, `(circe-chat-input "/msg foo bar")`? Is there a reason why you use these, instead of the respective commands (e.g. `circe-command-SAY`) directly? Convenience? Lack of documentation?

**Comment by kozross** [comment]
No, none of them do - I just feed a string straight to ``circe-chat-input`` (or used to, rather). I use these out of convenience - it's easier for me to type ``/php`` than remember that link or look it up all the time.

**Comment by jorgenschaefer** [comment]
You can use `(circe-command-SAY "hello world")` to get the same effect as `(circe-chat-input "hello world")`, without any possible confusion of the line being interpreted as a command or similar. Is that a better solution than `circe-chat-input`, or would you prefer to retain a direct interface to the input interpreter? :-)

**Comment by kozross** [comment]
I guess that works - I'll convert my code to using ``circe-command-SAY`` instead.

**Comment by jorgenschaefer** [comment]
Ok, glad to hear that works :-)

Please do not hesitate to open more issues if you have further questions or problems, and enjoy Circe!
