### ISSUE TITLE
Tracking displays somtimes shown buffer as having new messages

### ISSUE THREAD

**Issue by V155** [jorgenschaefer/circe#186]
As you can see in this screenshot tracking shows new messages in #archlinux.de even if its the opened/displayed buffer 
https://paste.xinu.at/u0SG/

**Comment by jorgenschaefer** [comment]
Thanks for the report!
Are you using multiple frames?

**Comment by V155** [comment]
If a frame is what is produced with C-x 2
Yes I do :-) 

Am 23. Juni 2015 11:25:07 MESZ, schrieb "Jorgen Schäfer" <notifications@github.com>:

**Comment by jorgenschaefer** [comment]
Those are called "windows" in Emacs, and what the rest of the world calls "windows" is what Emacs calls frames (yes, it's silly). You can create new frames with `C-x 5 2`. So I guess no, you don't. That is very strange. :-)

`tracking.el` should not add a buffer if it is shown in a window. Does `(get-buffer-window (current-buffer))` return `nil`?

**Comment by V155** [comment]
No it does return the name of the window. Im using emacs --daemon and emacsclient -c perhaps this is like using windows?

**Comment by jorgenschaefer** [comment]
tracking.el does use that line exactly to check if it should show a tracking indicator. Something seriously fishy is going on there. :-(

**Comment by V155** [comment]
Ok.  I will check my setup and come back if the Problem persists

**Comment by jorgenschaefer** [comment]
I was about to ask if this is happening regularly – thanks for looking into this!

**Comment by V155** [comment]
The problem persists after cleaning my config and fixing some errors in it.
And yes I would say that it happens regularly perhaps because the emacs frame? got no
focus all the time. 
Im using a tilig wm and can still read the window whether it got
focus or not.
But perhaps its something else :-)

Is there something I can test to assist you?

**Comment by jorgenschaefer** [comment]
Ah. It is quite possible that Emacs does not know that your window manager is actually displaying the Emacs frame.

Can you try using a different value for `tracking-frame-behavior`? Either `0` or `t` might work better.

**Comment by jorgenschaefer** [comment]
Did that solve the problem for you? :-)

**Comment by V155** [comment]
Yes I set tracking-frame-behavior to t and its fixed now. Thanks!
