### ISSUE TITLE
Tracking indicator displays too many buffers

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/circe#188]
ZNC playback adds every single buffer to the tracking indicator with the highlight (when I've been the last one to set the topic) or server face (because it spits out the nick listing). Bisection revealed that the commit introducing this behaviour is https://github.com/jorgenschaefer/circe/commit/1e5c8426d80788a809fd97167a3dc4add55536d2, but I have no clue why it would be the culprit. Any thoughts on this?

**Comment by jorgenschaefer** [comment]
Strange. Doesn't appear to be happening here – is it related to your local changes wrt. nick highlighting maybe (if there are any left)?

Stab in the dark, could you remove the `:nick` line from that function and see if that works better?

**Comment by jorgenschaefer** [comment]
Correction, reproduced locally :-D

**Comment by wasamasa** [comment]
Thanks, that fixed it for me as well.
