### ISSUE TITLE
Getting raw events displayed at startup

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/circe#189]
Here's the first three lines of every server buffer I get from Circe:

```
*** Connecting...
*** [conn.connected from nil] 
*** [irc.registered from wasamasa] 
```

Every other `irc.el` event appears to have display handlers set to it with the exception of `conn.connected` and `irc.registered`.

**Comment by jorgenschaefer** [comment]
Hah, good catch!

**Comment by wasamasa** [comment]
I can also spot `*** [nickserv.identified from nil]` for Bitlbee.

**Comment by wasamasa** [comment]
Thanks,
