### ISSUE TITLE
Face merging appears to be misapplied in Circe buffers

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/circe#190]
I've investigated into #187 lately and needed a way of discerning server messages from other messages. The suggestion given was to check for the face at point. Upon using `M-x describe-char` on server messages and highlights in server buffers I've noticed that the values of the `face` property are single-item lists with the respective face inside them which seems a bit unusual to me. I'd expect a list to be used when there's more than one face involved. Currently I'm comparing the value of the face property against `'(circe-server-face)` but this feels wrong to me.

**Comment by jorgenschaefer** [comment]
Does `(memq 'circe-server-face (face-at-point nil t))` do what you want?

(No, I do not know why Emacs insists of making trivial things like these so complicated.)

**Comment by wasamasa** [comment]
Yup, that looks good. Still investigating why the face merging doesn't appear to work...

**Comment by wasamasa** [comment]
Apparently the `add-text-properties` function wipes out any previously used property with the same name, this can be verified by checking its sources as it's using the internal `add_text_properties_1` function with a `TEXT_PROPERTY_REPLACE` flag. Same applies to `put-text-property` and `set-text-properties`.

The sole exception is `add-face-text-property` which can both prepend and append a face name to a list of faces associated with the face property, so I assume that's what you'd want to use to do this properly. I found it trivial to replace the usage of `add-text-properties` for the three non-default variants of `circe-highlight-nick-type` in `circe--output-highlight-nick`, currently I'm working on understanding how exactly `circe--highlight-extend-properties` works for the `sender` type (I suspect I could replace it with a specialized variant only working for the face property, but am not sure yet). Maybe `font-lock-append-text-property` could be replaced for `add-face-text-property` with APPEND set as well...

**Comment by jorgenschaefer** [comment]
Interesting. I thought that's what `add-text-properties` should do, but apparently I confused it with `add-face-text-property`. Circe used to have some magic code in it to dispatch here, but I guess I confused myself.

Thanks for digging through this and debugging it!
