### ISSUE TITLE
Other people's nick changes aren't appearing

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/circe#191]
I can see my own, but not others. This kind of thing happened before, but for both me and others.

**Comment by jorgenschaefer** [comment]
Thanks for the report! Yeah, `circe-display-NICK` is called when the nick change is already processed by `irc.el`, so needs to use `(circe-user-channels new-nick)` instead of the old nick. Will get around to that function eventually while I'm redoing all display handlers.
