### ISSUE TITLE
Command completion doubles the slash

### ISSUE THREAD

**Issue by david-christiansen** [jorgenschaefer/circe#193]
When completing a command with `completion-at-point`, it adds an extra slash. This means that it's easy to accidentally write something in a channel rather than /msg it to someone.

Example:
```
#chan> /ms
```
then pressing tab yields
```
#chan> //MSG 
```
I would expect it to not do that.

**Comment by wasamasa** [comment]
Cannot reproduce this on HEAD. What Circe and Emacs version are you on?

**Comment by david-christiansen** [comment]
Circe is latest from MELPA, Emacs is 24.4. Perhaps it's some kind of interaction with other packages...

**Comment by david-christiansen** [comment]
Hmm, just tried it in `emacs -q` and it works correctly. The bug must be somewhere else. Sorry!

**Comment by david-christiansen** [comment]
I suppose I should poke at Helm's handling of /.

**Comment by jorgenschaefer** [comment]
Thank you for the report anyhow. It's always good to report possible problems :-)

If you find out what is causing this, and if Circe can do something (relatively) easy to avoid the problem, please do let us know!

**Comment by david-christiansen** [comment]
Thanks! You run a tight ship here!

**Comment by wasamasa** [comment]
Are you by any chance using `helm-mode`? It does not only handle general `completing-read` operations,  but also hooks itself into the more generic completion mechanism as provided by Emacs.  I have [a workaround](https://github.com/wasamasa/dotemacs/blob/master/init.org#completing-read-behaviour) for it in my config.

**Comment by david-christiansen** [comment]
That fixed it for me! Thanks!

**Comment by jorgenschaefer** [comment]
@wasamasa, do you think something like the following in Circe would be useful? Or is that too intrusive?

```Lisp
(eval-after-load "helm-mode"
  '(setq helm-mode-no-completion-in-region-in-modes
         (append helm-mode-no-completion-in-region-in-modes
                 '(circe-channel-mode circe-query-mode circe-server-mode))))
```

**Comment by david-christiansen** [comment]
I don't think it's a good idea to tweak the user's Helm config like that, personally. Better to have an FAQ entry or something.

**Comment by jorgenschaefer** [comment]
Hm. Makes sense. An FAQ entry would be good :-)

**Comment by wasamasa** [comment]
Doesn't the wiki handle this purpose already? I'm not sure where exactly I'd put that tip into it though...

**Comment by wasamasa** [comment]
Oh and yes, I'm in favour of not altering helm behaviour as it's unexpected and could even be desired as alternative "input method", similar to a related issue with company-mode. It sure looks like `completion-in-region-functions` is a variable modes are fighting each other for, just to provide less horrible UI for this part of Emacs.

**Comment by jorgenschaefer** [comment]
Could someone who knows Helm and can test this update the [Configuration](https://github.com/jorgenschaefer/circe/wiki/Configuration) section in the wiki accordingly?

**Comment by wasamasa** [comment]
I've added a [tab completion](https://github.com/jorgenschaefer/circe/wiki/Configuration#tab-completion) section to the wiki.

**Comment by jorgenschaefer** [comment]
Thank you!

**Comment by david-christiansen** [comment]
Thanks, all!
