### ISSUE TITLE
Correct add-face-text-property compatibility definition in circe-color-nicks.el

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/circe#195]
circe-color-nicks.el defines `add-face-text-property` when it is not defined, as that function as added in 24.4 only. The current compatiblity definition uses `circe-merge-text-properties`, which is not defined anymore. This should be replaced by a function that handles merging correctly there.

**Comment by wasamasa** [comment]
Oh, I wasn't aware of this when I've made liberal use of `add-face-text-property` in circe.el. Perhaps the compatibility definition should be put there instead?

**Comment by jorgenschaefer** [comment]
Yes, that'd be good. A fixed version, too. :-D
