### ISSUE TITLE
Network names matched case-sensitively

### ISSUE THREAD

**Issue by TaylanUB** [jorgenschaefer/circe#196]
A network name argument passed to the `circe` function will be matched case sensitively.  Pretty annoying during interactive use.

In the past, I experienced log files being named (cased) differently depending on what I passed to the `circe` function.  It would be great if we could avoid this this time, while fixing this issue.  I.e. passing "freenode" should lead to logfiles named `#channel@Freenode` and not `#channel@freenode`.

**Comment by jorgenschaefer** [comment]
Good idea.
