### ISSUE TITLE
Connections to custom hosts

### ISSUE THREAD

**Issue by defanor** [jorgenschaefer/circe#197]
Connection to servers which are not listed in `circe-networks` appears to be broken in Circe 20150704.617 from melpa; apparently a minor bug somewhere in parameters, getting the following error message:

```
irc-connect: Must specify a :service to connect to
```

To reproduce -- `M-x circe RET irc.freenode.net RET RET`.

**Comment by jorgenschaefer** [comment]
Oops :-D Thank you!
