### ISSUE TITLE
Package lui 1.6 not available

### ISSUE THREAD

**Issue by nlamirault** [jorgenschaefer/circe#202]
if i try to install circe from melpa stable [1] , i've got this error : 

```lisp
Debugger entered--Lisp error: (error "Package `lui-1.6' is unavailable")
  signal(error ("Package `lui-1.6' is unavailable"))
  error("Package `%s-%s' is unavailable" lui "1.6")
  package-compute-transaction(([cl-struct-package-desc circe (1 6) "Client for IRC in Emacs" ((lui (1 6)) (lcs (1 1))) tar "melpa-stable" nil nil nil]) ((lui (1 6)) (lcs (1 1))) ([cl-struct-package-desc circe (1 6) "Client for IRC in Emacs" ((lui (1 6)) (lcs (1 1))) tar "melpa-stable" nil nil nil]))
  package-compute-transaction(nil ((circe)))
  package-install(circe)
```

Circe seems depends on **lcs 1.1** and **lui 1.6**, they are not available in melpa stable.

[1] http://stable.melpa.org/#/circe

**Comment by jorgenschaefer** [comment]
Meh. Thank you for the report.

This is a problem with the way MELPA and MELPA stable works. As lui and lcs have been removed from MELPA (they're now part of Circe in the development version), they are also gone from MELPA stable, so the stable version of Circe is not installable anymore.

There will be a new version of Circe released in two weeks, I don't think this is fixable until then, I'm afraid. :-(

**Comment by nlamirault** [comment]
OK thanks !

**Comment by jorgenschaefer** [comment]
As there will be a release tomorrow, I'll close this issue. Thanks again for the report, even though we couldn't really fix it.
