### ISSUE TITLE
Demo screenshot in the README

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/circe#204]
Would be nice to have a demo screenshot in the README.

**Comment by wasamasa** [comment]
![](http://i.imgur.com/BmM4EC7.png)

**Comment by wasamasa** [comment]
![](http://i.imgur.com/Ax3Iy15.png)

Here's another one.

**Comment by jorgenschaefer** [comment]
Thanks!

I never understood what it is with people and their dark backgrounds, but it seems common, so I guess this is more typical than whatever I could come up with :-)
