### ISSUE TITLE
README feature list is missing modules

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/circe#205]
The feature list in the README is missing some features added by modules.

**Comment by jorgenschaefer** [comment]
Note to self: Check if the auto-linking is mentioned

**Comment by wasamasa** [comment]
I went over all the code for the following list:

# Circe

## circe-chanop.el

- Common channel operator commands

## circe-color-nicks.el

- Color nicknames and mentions in unique colors

## circe-highlight-all-nicks.el

- Color nicknames and mentions in the same color

## circe-lagmon.el

- Lag monitor for auto-reconnecting

## circe.el

- Ignore list (filters out) and Fool list (hides and allows toggling
  display of hidden messages)
- Topic changes can be displayed as diff
- TLS support
- Nickserv authentication, ghosting, nick re-gain
- SASL authentication
- Query flooding protection
- Tab completion
- Smart filter (hide JOIN, PART, QUIT, NICK for inactive users)
- Nick highlighting in various flavours
- Customizable format strings for general appearance
- Automatic message splitting
- Customizable Auto-Join (no Auto-Rejoin though...)
- Netsplit detection


- Sensible defaults
- Active development
- Join us over at #emacs-circe

## irc.el

- Easily hackable library for writing IRC bots

## lcs.el

- Helper library for the shortening feature

## lui-autopaste.el

- Automatic paste detection and pastebin

## lui-format.el

- Flexible formatting support

## lui-irc-colors.el

- mIRC-style color support

## lui-logging.el

- Logging

## lui.el

- Reusable abstraction for building line-oriented interfaces
- Linkification of URLs and other unique identifiers (like RFCs or
  xkcd strips)
- Flexible filling and time stamps
- Flyspell, =show-paren-mode= and =blink-matching-paren= support

## make-tls-process.el

- TLS

## shorten.el

- Shorten a list of strings to their unique prefix

## tracking.el

- Mode line channel activity tracker

**Comment by jorgenschaefer** [comment]
Awesome, thank you for the work! I transferred the important ones to the README. If you want to preserve the full list, I think the wiki would be a good place. :-)

**Comment by wasamasa** [comment]
No, that's fine.
