### ISSUE TITLE
lui-button-issue-tracker seems to have no effect

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/circe#209]
I'm fairly sure the feature of a set `lui-button-issue-tracker` fontifying `#123` links used to work, but couldn't make it do that when bisecting to the commit introducing the feature, https://github.com/jorgenschaefer/circe/commit/b847f6e9b8d0b1365647bbb3265c9fa9aa065aa0.

**Comment by jorgenschaefer** [comment]
Thanks for the report! The regexp was missing a whole question mark :-D No idea why I forgot that back then. I thought it was working, too.
