### ISSUE TITLE
Highlighting doesn't catch mIRC color codes and is applied the wrong way around

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/circe#210]
I've observed two minor issues:

- `^C3wasamasa^C` is not highlighted at all although it certainly reads like my nickname.  Probably a case of boundaries that lead to a mismatch.  Maybe this could be fixed by applying colors *before* doing nick highlighting instead of doing it afterwards?
- `^C3foo wasamasa bar^C` is colored throughout with the highlighting face *under* it.  This happens because `lui-irc-propertize` uses `font-lock-prepend-text-property` after the highlighting pass which puts it in front and therefore prioritizes it.  Replacing it with `font-lock-append-text-property` fixes it and puts a highlight on the nick name while keeping the rest colored as expected.

**Comment by jorgenschaefer** [comment]
Good catch.

**Comment by jorgenschaefer** [comment]
Applying colors _before_ nick highlighting would fix both issues at the same time, wouldn't it?

**Comment by wasamasa** [comment]
Sounds about right.
