### ISSUE TITLE
Tracking updates in the currently selected window are not propagated to other windows

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/circe#215]
I have two windows open with tracking enabled.  The unfocused window has a seemingly frozen tracking indicator snapshot, the focused one keeps getting updates and eventually has more channels displayed there than the unfocused window.  Switching window focus or buffers rectifies the situation.  Must be a `force-mode-line-update` without the optional argument set somewhere.

**Comment by jorgenschaefer** [comment]
tracking.el has had a history of uncovering problems with Emacs' update code there …

**Comment by wasamasa** [comment]
```elisp
    ;; Update mode line. See `force-mode-line-update' for the idea for
    ;; this code. Using `sit-for' can be quite inefficient for larger
    ;; buffers.
    (dolist (w (window-list))
      (with-current-buffer (window-buffer w)))
```

```
Force redisplay of the current buffer's mode line and header line.
With optional non-nil ALL, force redisplay of all mode lines and
header lines.  This function also forces recomputation of the
menu bar menus and the frame title.
```

**Comment by jorgenschaefer** [comment]
The former piece of code is from `tracking-next-buffer`, so likely unrelated to your issue. `tracking-add-buffer` uses `sit-for` – maybe it should (also) use `force-mode-line-update`? It used to, but that didn't work in all cases.

**Comment by wasamasa** [comment]
Replacing `(sit-for 0)` with `(force-mode-line-update t)` in `tracking-add-buffer` seems to fix this.
