### ISSUE TITLE
(lui-read-only-output-p nil), RET becomes ^M

### ISSUE THREAD

**Issue by koo5** [jorgenschaefer/circe#217]
i am using circe with (lui-read-only-output-p nil), which allows me to edit the backlog. It works rather well, except that pressing return in the backlog area inserts "^M" instead of a newline. 

I have a satisfactory workaround, but submitting the issue anyway, as promised.

http://23.102.163.145/.emacs

> emacs --version
GNU Emacs 24.4.1

 F1 k RET:
http://paste.ubuntu.com/12240090/

screenshot:
http://paste.ubuntu.com/12240147/

**Comment by wasamasa** [comment]
I am able to reproduce this, checking what exactly is going on here.

**Comment by wasamasa** [comment]
OK, this is sort of silly.  What happens in this moment is that `RET` is not interpreted as "Run a command inserting a newline", but as "Insert the value of the key as is into the buffer".  Given that `RET` happens to be `C-m` which is `\r` and the coding system of the IRC buffer is most certainly set to Unix-style newlines which are `\n`, your input is displayed as `^M`. If you would use `C-j`, chances are you'd get a newline inserted. If you want to learn more about this, https://en.wikipedia.org/wiki/Control_character is an okayish introduction.

As `lui-send-input` is bound to `RET`, it should be OK to replace it calling `self-insert-command` with `newline` to fix this.

@forcer Any thoughts on this?

**Comment by jorgenschaefer** [comment]
Wrong dude there :-)

And yes, probably should just run `newline` there. Good catch.
