### ISSUE TITLE
Any way to surface "Buffers with unread messages" ? 

### ISSUE THREAD

**Issue by bradens** [jorgenschaefer/circe#219]
Maybe i'm totally missing something, but is there any way to show (say in the buffer list) which circe buffers have unread messages in them?

Thanks!

**Comment by wasamasa** [comment]
Circe comes with a tracking module that shows buffers with new messages in them in the modeline.  You should be able to spot an indicator looking like `[#a,#f,#cc]` in it with `#a`, `#f` and `#cc` being abbreviated channel names.

**Comment by bradens** [comment]
Weird, not seeing that.  I'll have to look into why that is.  Thanks.

**Comment by bradens** [comment]
Nevermind, this is a dupe of #137 I didn't realize that circe doesn't support powerline right now.

**Comment by jorgenschaefer** [comment]
Can I vote for "powerline does not support Circe yet"? :-D

**Comment by bradens** [comment]
:smile: sure

**Comment by NightMachinary** [comment]
@jorgenschaefer How do I disable `circe` touching my modeline?
![image](https://user-images.githubusercontent.com/36224762/121161097-e720c700-c861-11eb-8b51-bfd53d12cdd0.png)

Disabling `tracking-mode` doesn't hide the above.
