### ISSUE TITLE
"Unknown function `with-circe-server-buffer'" upon calling `circe-reconnect`

### ISSUE THREAD

**Issue by riccardomurri** [jorgenschaefer/circe#223]
When I call `circe-reconnect`, I get an error backtrace stating that function `with-circe-server-buffer` is unknown.  Of course, `with-circe-server-buffer` *is* defined, but it's a macro.

I byte-compile every `.el` file automatically upon save, and I think the root problem stems from the byte-compiler: `circe-reconnect` is defined around line 1080, *before* the `defmacro with-circe-server-buffer` so (I guess) the byte-compiler mistakes the call for a function call and does not macroexpand it.

**Comment by jorgenschaefer** [comment]
Thanks for the report! Seems few of the regulars compile Circe. Heh. :-) Merged your PR.
