### ISSUE TITLE
Moving between links with <TAB> stops working with this specific URL

### ISSUE THREAD

**Issue by felipe-barros** [jorgenschaefer/circe#231]
When links including `/rfc` are part of the URL, it seems I can move backward with <kbd>S-TAB</kbd> just fine, but when moving forward the point gets locked in the line, and keeps moving back and forward between the beginning of the link and the column of the first `/r`.

The line where I experienced this:

```
<Ella> daemon: Rfc 2016 - World Wide Web Consortium <
    http://www.w3.org/Protocols/rfc2616/rfc2616.txt >
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! This looks like some bad interaction between buttonizing URLs and other links. Hrm.

**Comment by wasamasa** [comment]
Apparently `forward-button` finds the next button, then goes to its start.  If there's nested buttons like in this example, the start belongs to the outer button, so `TAB` does get caught in a loop.

Not sure how to solve this properly.  My hunch is that nested buttons are silly anyways, so I'd just forbid them by checking the context when a button is about to be inserted and abort if it's inside another button.

**Comment by wasamasa** [comment]
See https://github.com/jorgenschaefer/circe/commit/b9752873827fc5bae38b421eb37e99ed8b28dd6c?w=1 for a solution.  I'm not sure whether changing the buttonization order breaks something elsewhere, so I've done it in another branch.

**Comment by jorgenschaefer** [comment]
Sounds good to me, really. Just push it to master. :-) And thank you!

**Comment by wasamasa** [comment]
Done.

**Comment by felipe-barros** [comment]
Thanks! :+1:
