### ISSUE TITLE
Could lui.el be split into a separate project?

### ISSUE THREAD

**Issue by ryuslash** [jorgenschaefer/circe#235]
Hi,

I'm trying to use `lui-mode` to improve the interface of another Emacs application. It is an application that functions a lot like IRC, so I thought it would be an excellent match. It's just a bit weird to have to depend on an IRC application to install an application in Emacs that actually has nothing to do with IRC.

So I was wondering if it is possible to split the lui parts into a separate project (or at least package). Not right away of course, I don't want to add to the burden of maintenance by getting you to split it into a separate project and having to maintain two, instead of one, project before knowing if it's actually going to go through. But I was curious since it seems useful to other projects as well.

Thanks in advance for your time.

Cheers,

Tom

**Comment by jorgenschaefer** [comment]
Hello! This actually used to be the case – lui was its own package with its own releases. In ten years, not a single package came along to use lui outside of Circe. (I think there was one, at some point, but it got discontinued quickly.)

As it happens, MELPA Stable is currently the most useful way to distribute packages, and MELPA Stable can only do releases based on tags for the whole repository, so we had to release lui, circe, etc. all with the same version number all at the same time, which became silly. The "correct" solution would be to develop each package in its own Github repository, but as no one else seemed to be using our packages, and we develop them together, that feels highly annoying.

So while in theory I fully agree and would love to split out the packages again, there are currently technical reasons outside of our control (MELPA Stable) that prevent us from doing so.

If you have good ideas on how to fix this, I'm all ears!

**Comment by ryuslash** [comment]
Hi, 

Thanks for your reply.

I think the only real solution is the "correct" solution. For now I think it's best to keep things as they are, but if this other project gets off the ground, would you be willing to split `lui.el` into a separate project/repository?

Personally I use Circe anyway, so it's not a problem for me. I have no idea however if anyone else uses the project I'm doing this for, aside from the person whose project it is.

I will keep thinking about this in the mean time, if I come up with any ideas I'll be sure to let you know.

**Comment by jorgenschaefer** [comment]
> if this other project gets off the ground, would you be willing to split `lui.el` into a separate project/repository?

It's possible, but no promises.

**Comment by ryuslash** [comment]
I understand. We'll see how it goes. Thank you.
