### ISSUE TITLE
nickserv-password not pass in properly on initial connection?

### ISSUE THREAD

**Issue by galderz** [jorgenschaefer/circe#239]
Hi, these are my IRC channels:

````
(load-file "~/.private.el")

(setq circe-network-options
      `(("Freenode"
         :nick "..."
         :channels (...)
         :nickserv-password ,freenode-password
         )))
```

I have also created this command for connecting to IRC channels:

```
(defun circe-connect-all ()
  "Connect to IRC"
  (interactive)
  (circe "Freenode"))
```

So, some of those channels require the password, but when I execute `circe-connect-all`, I see messages like:

```
-NickServ- This nickname is registered. Please choose a different
    nickname, or identify via /msg NickServ identify <password>.
-Server Notice- [freenode-info] why register and identify? your IRC
    nick is how people know
    you. http://freenode.net/faq.shtml#nicksetup
*** #<name> Cannot join channel (+r) - you need to be
    identified with services
```

However, if I manually then going and do: `/JOIN #<name>`, then it works fine.

I'm using Circe 2.1, any ideas how to debug this further or what could be wrong?

Cheers,
Galder

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! Sorry for the late response, I was on vacation. Circe will join channels in `:channels` right after registration, before authentication with nickserv is complete. If you change the options to `:channels (:after-auth "#<name>")`, does that fix the problem?

**Comment by danielxvu** [comment]
Not OP, but your tip worked for me. :) Been watching this one to find out the answer too; perhaps it could be added to the Configuration page under Network Configuration in the wiki?

**Comment by jorgenschaefer** [comment]
Not a bad idea (volunteers welcome :-)). Also, I think Circe could be smarter about the default … Let me make a ticket for that.

**Comment by galderz** [comment]
That worked!! Thx @jorgenschaefer :)

I've edited the [wiki](https://github.com/jorgenschaefer/circe/wiki/Configuration#join-channels-requiring-identification) to add a section on this.

**Comment by jorgenschaefer** [comment]
Thank you! :-)
