### ISSUE TITLE
Installation via instructions in README.md fail

### ISSUE THREAD

**Issue by bigfaceworm** [jorgenschaefer/circe#243]
When following the directions to do

   M-x package-install RET circe RET

you fail with the message:

    url-insert-file-contents: http://stable.melpa.org/packages/lcs-1.5.el: Not found

And the package doesn't seem to exist - the files appear to be a part of circe itself.

**Comment by wasamasa** [comment]
Huh, I cannot reproduce this in a freshly set up Emacs because the recipe does not mention any dependencies.  Could you please check whether deleting `~/.emacs.d/elpa/archives/melpa-stable/archive-contents` and refetching package information with `M-x list-packages` solves the problem?

**Comment by bigfaceworm** [comment]
That does it, thanks.  Didn't know about that.  I'm pretty new to using
package.


TJ

On Tue, Feb 2, 2016 at 12:17 PM, Vasilij Schneidermann <
notifications@github.com> wrote:

> Huh, I cannot reproduce this in a freshly set up Emacs because the recipe
> does not mention any dependencies. Could you please check whether deleting
> ~/.emacs.d/elpa/archives/melpa-stable/archive-contents and refetching
> package information with M-x list-packages solves the problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jorgenschaefer/circe/issues/243#issuecomment-178799955>
> .
>



-- 
Trey Jackson
bigfaceworm@gmail.com

"Like any truly useful program, `hello' contains a built-in mail reader."
-- GNU's Bulletin, July 1996

**Comment by wasamasa** [comment]
Cool, thanks for confirming.

**Comment by jorgenschaefer** [comment]
Hm. I've seen this before – MELPA seems to sometimes generate a broken archive-contents. Maybe they're not creating it atomically? In any case, glad it works now, enjoy Circe! :-)
