### ISSUE TITLE
Chat history not inserted

### ISSUE THREAD

**Issue by galderz** [jorgenschaefer/circe#244]
I have enabled history chats using the instructions [here](https://github.com/jorgenschaefer/circe/wiki/Configuration#logging) and I see that it creates a `~/.logs` folder with the history of the chats.

That section also says:

> When you enter the same chat again the log will be inserted.

I don't see that happening in Circe 2.1 and in fact it'd be very useful to have since right now the only way I can search back through history is by going to the command line and doing find+grep.

Is there anything that has to be enabled extra to get the history from previous chats inserted? I do see chat logs present in `~/.logs` folder.

Cheers,
Galder

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question … I have no idea why that sentence was in the docs, I have no recollection of such a feature (sadly). This would be a nice feature to have, though! Sadly, this is non-trivial, as the log files do not retain all the information in the IRC protocol, so replaying the logs won't really give the same information or even coloring.

I know a few people who use bouncers like znc to stay on IRC and also to get a replay of the conversations they missed. That's likely a more effective solution than to try and replay log files, given the state of the IRC protocol.

Sorry the documentation confused you like this.

**Comment by wasamasa** [comment]
I've seen implementations of this that restricted themselves to private conversations and a configurable backlog size to give you more context for the conversation.  Given this requirement, status changes and nick colours would not be necessary.

**Comment by jorgenschaefer** [comment]
Anyone want to open a feature request issue? :-)

**Comment by ryuslash** [comment]
This would be excellent, we have a "load more" button in emacs-slack to retrieve more of a conversation, but just like with the delete/modify actions it would be great if lui could offer some help in managing this.

**Comment by galderz** [comment]
I think @wasamasa opened a feature request a few days ago. I'll close this for now. Thanks all for the answers.

**Comment by jorgenschaefer** [comment]
Thank you for bringing this idea up! :-)
