### ISSUE TITLE
work around, or fix, http://debbugs.gnu.org/cgi/bugreport.cgi?bug=22120

### ISSUE THREAD

**Issue by offby1** [jorgenschaefer/circe#247]
Basically: bind `gc-cons-threshold` to `most-positive-fixnum` inside `lui-adjust-undo-list`.  Apparently it's Not Good®™ to mess with the undo list.  Details are in [the Emacs bug](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=22120).
```
diff -uw /home/ec2-user/.emacs.d/elpa/circe-20160226.837/lui.el\~ /home/ec2-user/.emacs.d/elpa/circe-20160226.837/lui.el
--- /home/ec2-user/.emacs.d/elpa/circe-20160226.837/lui.el~     2016-02-27 02:43:25.260202552 +0000
+++ /home/ec2-user/.emacs.d/elpa/circe-20160226.837/lui.el      2016-03-07 03:37:00.240409245 +0000
@@ -960,7 +960,8 @@
   ;; Thanks to ERC for the idea of the code.
   ;; ERC's code doesn't take care of an OLD-BEGIN value, which is
   ;; necessary if you allow modification of the buffer.
-  (let* ((adjust-position (lambda (pos)
+  (let* ((gc-cons-threshold most-positive-fixnum)
+         (adjust-position (lambda (pos)
                             (if (and (numberp pos)
                                      ;; After the boundary: Adjust
                                      (>= (abs pos)
```

**Comment by jorgenschaefer** [comment]
Thank you! I actually accidentally applied a local fix I was testing in effbb63 … vc-mode is not very forthcoming with warnings such as these.

Incidentally, Emacs Lisp is the only interpreted language I know where you can report "when I do this, it causes a segfault", and the response is "well, don't do that, then".
