### ISSUE TITLE
Multiple connections with diff domain name on same host creates unnecessary buffers

### ISSUE THREAD

**Issue by bandresen** [jorgenschaefer/circe#250]
Hey, I need a small preamble to set it up:
I have a ZNC service running with which I connect to three different IRC servers. (Only one service, so they share IP + Port. The username is unique.)
I added three distinct domains with which I tried to distinguish the ZNC connections for buffer naming.

circe connects to freenode.foobar.tld with user/freenode:passwd which is set up to connect to freenode irc
-> everything great, unique username+pw combination accepted, MOTD by freenode and joining channels on freenode works

circe connects to mozilla.foobar.tld with user/mozila:passwd which is set up to connect to mozilla irc
-> stuff gets weird: unique username+pw combination gets accepted (wrong gets denied)
the MOTD is by the previous freenode server
joining channel on mozilla.foobar.tld will join channels on mozilla irc (good!)
for every open channel another buffer is created on circe irc connection

example:
join channel blabla on mozilla creates buffer blabla@mozilla and blabla@freenode but they both actually are connected in the background to mozilla

irc-debug-log is identical and shows the above (mozilla join attempt but answer comes from freenode)

I tried up to 4 simultaneous connections and I can chat correctly but I have 4x the buffers I'm supposed to have

Thanks in advance!

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report!

Just to clarify, `irc-debug-log` creates buffers per connection. You see answers from Freenode in the `*IRC Protocol mozilla.foobar.tld:6667*` buffer?

**Comment by bandresen** [comment]
Yes, in the *IRC Protocol mozilla* buffer I see S=wilhelm.freenode.net.

**Comment by jorgenschaefer** [comment]
That is *really* strange. That means that a process connected to the domain `mozilla` sends lines from the freenode server. I'd love to look at that myself, but I can't reproduce the problem locally.

Could you post the output of `M-x list-processes`?

**Comment by bandresen** [comment]
Provided list-processes on irc. Turns out problem is on user end and is a configuration issue. Multiple server conncetions to the same host with the same port work fine and cause no strangeness.

All you need is following the documentation for circe-network-options
