### ISSUE TITLE
Freenode host name check fails

### ISSUE THREAD

**Issue by zenon** [jorgenschaefer/circe#251]
Hi,

I just got the current version from melpa, because the 1.6 (that I used before) doesn't know SASL.

Now, I get an error message that I don't understand:

*** Connecting...
-Server Notice- *** Looking up your hostname...
-Server Notice- *** Checking Ident
-Server Notice- *** Found your hostname
-Server Notice- *** No Ident response
*** Error: Closing Link: 127.0.0.1 (Connection timed out)

In the IRC Protocol ..

S: :kornbluth.freenode.net NOTICE * :*** Looking up your hostname...
E: "NOTICE" "kornbluth.freenode.net" "*" "*** Looking up your hostname..."
E: "irc.notice" "kornbluth.freenode.net" "*" "*** Looking up your hostname..."
S: :kornbluth.freenode.net NOTICE * :*** Checking Ident
E: "NOTICE" "kornbluth.freenode.net" "*" "*** Checking Ident"
E: "irc.notice" "kornbluth.freenode.net" "*" "*** Checking Ident"
S: :kornbluth.freenode.net NOTICE * :*** Found your hostname
E: "NOTICE" "kornbluth.freenode.net" "*" "*** Found your hostname"
E: "irc.notice" "kornbluth.freenode.net" "*" "*** Found your hostname"
S: :kornbluth.freenode.net NOTICE * :*** No Ident response
E: "NOTICE" "kornbluth.freenode.net" "*" "*** No Ident response"
E: "irc.notice" "kornbluth.freenode.net" "*" "*** No Ident response"
S: ERROR :Closing Link: 127.0.0.1 (Connection timed out)
E: "ERROR" nil "Closing Link: 127.0.0.1 (Connection timed out)"
E: "conn.disconnected" 
S: :kornbluth.freenode.net NOTICE * :*** Looking up your hostname...

Can you help?

Thank you, zenon

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This looks entirely weird – Circe connects, but does not send any commands. Did you restart Emacs after the upgrade?

**Comment by zenon** [comment]
Yes.

**Comment by kgunders** [comment]
I sometimes see extensive delays, apparent hangs, but eventually will connect.  Other times connects fine, although noticeably slower than rcirc.  Initially I suspected Freenode network issues but after seeing this... maybe not?

**Comment by jorgenschaefer** [comment]
Hm. The protocol log is missing entries, there should be at least a `"conn.connected"` event at some point. Was the log truncated at the top?

> And I'm utterly impressed by your response speed!

Thanks. But you got lucky and I was at the computer with some time at that moment :-)

**Comment by zenon** [comment]
No. The IRC Protocol buffer starts with

S: :kornbluth.freenode.net NOTICE * :*** Looking up your hostname...

**Comment by zenon** [comment]
Achja. Emacs 24.4.1 unter, räusper, Windows 7.

**Comment by jorgenschaefer** [comment]
That is _very_ weird – how are you setting `irc-debug-log`? Is that set before you start connecting?

**Comment by zenon** [comment]
Yes, in .emacs.

**Comment by jorgenschaefer** [comment]
This is definitely broken. The log for me starts like this:

```
E: "conn.connected"
C: CAP LS
C: NICK forcer
C: USER forcer 8 * http://www.jorgenschaefer.de/
S: :adams.freenode.net NOTICE * :*** Looking up your hostname...
```

So you're missing the client-side handshake, but also the whole connected event. I have no idea how that can happen.

Can you share your Emacs configuration?

**Comment by zenon** [comment]
(setq inhibit-startup-screen 1)
(setq initial-scratch-message "")
(tool-bar-mode 0)
(tooltip-mode 0)
(menu-bar-mode 0)
(size-indication-mode 1)
(column-number-mode 1)

(prefer-coding-system 'utf-8)
(show-paren-mode)

(desktop-save-mode 1)

; try to improve slow performance on windows.
(setq w32-get-true-file-attributes nil)


(defun frame-retitle (title)
  (modify-frame-parameters nil (list (cons 'name title))))

(frame-retitle "Emacs the Ultimate")

(defun recolor () 
  (set-background-color "black")
  (set-face-background 'default "black")
  (set-face-background 'region "black")
  (set-face-foreground 'default "white")
  (set-face-foreground 'region "gray60")
  (set-foreground-color "white")
  (set-cursor-color "red"))

(recolor)




; Marmelade
(require 'package)
(add-to-list 
 'package-archives
 '("marmalade" . "https://marmalade-repo.org/packages/"))
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(require 'ensime)
(add-hook 'scala-mode-hook 'ensime-scala-mode-hook)

; how??
;(setq org-export-with-properties '("Artist"))

;;; CIRCE

(setq irc-debug-log t) ; goes to *IRC Protocol ...*

(setq circe-network-options
      '(("Freenode"
	 :host "chat.freenode.net"; "kornbluth.freenode.net"; Frankfurt http://freenode.net/irc_servers.shtml
	 :port (8001 . 8002) ; All freenode servers listen on ports 6665, 6666, 6667, 6697 (SSL only), 7000 (SSL only), 7070 (SSL only), 8000, 8001 and 8002.
	 ; 
         :tls nil
         :nick "X"
	 :user "Y"
	 :realname "Z"
;         :sasl-username "X"
;         :sasl-password "XXXXXXXXX"
         :channels ("#xxxxxxx")
         )))

(setq circe-default-quit-message "")
(setq circe-default-part-message "")

(load "D:/others/el-presenti/el-presenti.el")
(load "D:/others/el-presenti/el-presenti-edit-mode.el")
(add-to-list 'auto-mode-alist '("\\.presenti\\'" . el-presenti-edit-mode))

**Comment by jorgenschaefer** [comment]
I am thoroughly confused here. Sorry, but I do not know what's going on there.

Can you confirm that `irc-debug-log` is `t` before running `M-x circe`? And you are absolutely positively sure that there is nothing more in the protocol buffer? (I am sorry for asking this, but this is absolutely confusing …)

**Comment by zenon** [comment]
Hm. Sorry for the difficulties.
Gibt's Wandsbek Gartenstadt ein Restaurant, wo ich Dir ein Abendessen ausgeben kann? :-))

**Comment by jorgenschaefer** [comment]
No difficulties, just being entirely confused here, and wish I could help. :-) Did you solve the problem?

Und kenne ich dich? :-D

**Comment by zenon** [comment]
No, didn't solve it. Switched back to 1.6 & don't use SASL, currently.

Nö. Ich Dich auch nicht. Aber direkt (und beim nach dem Essen) auf den Rechner starren hilf manchmal ...
Nur falls Du in den nächsten Tagen mal Hunger hast :-))
(Ich kann in Wandsbek Gartenstadt nichts empfehlen, ich fahr' da aber jeden Werktag durch, gegen 18:00.)

**Comment by jorgenschaefer** [comment]
Ok, tracing the code.

- The line `E: conn.connected` would be emitted by `irc-event-emit` called by `irc--sentinel`
- This event would also cause the initial registration. So it would seem to me as if the event is never generated
- `irc--sentinel` will emit an event or raise an error unless it is called with `deleted` or `killed`, which is unlikely here
- `irc--sentinel` is called by `make-network-process` in this particular case (no TLS)

So, either `make-network-process` does not register `irc--sentinel` as it should, or `irc--sentinel` is doing something weird.

To verify if `irc--sentinel` is called, could you evaluate this form and try to connect again:

```Lisp
(defun irc--sentinel (proc event)
  (message "SENTINEL: %S %S" proc event)
  (cond
   ((string-match "\\`failed" event)
    (irc-event-emit proc "conn.failed"))
   ((string-match "\\`open" event)
    (irc-event-emit proc "conn.connected"))
   ((string-match "\\`\\(connection broken\\|finished\\|exited abnormally\\)"
                  event)
    (irc-event-emit proc "conn.disconnected"))
   ((string-match "\\`\\(deleted\\|killed\\)" event)
    nil)
   (t
    (error "Unknown event in IRC sentinel: %S" event))))
```

This should result in at least one line in `*Messages*` starting with `SENTINEL:` – what do those lines say?

If there is no such a line, what version of Emacs are you using?

> Ich kann in Wandsbek Gartenstadt nichts empfehlen, ich fahr' da aber jeden Werktag durch, gegen 18:00. Und ich gehe nicht davon aus, dass Du dazu Zeit hast. Wollte es aber wenigstens vorschlagen. :-)

Man könnte sich durchaus mal auf ein Getränk (Bier o.ä.) treffen. Mit der U1 wäre der Feuervogel an der Wandsbeker Chausee eine Option, mit der U3 das Big Easy bei Barmbek. Je nachdem, wie du da durchfährst. Ich bestehe auch nicht auf einer Einladung, aber "hallo" sagen ist ja nicht verkehrt :-D

**Comment by zenon** [comment]
No sentinel at all in *Messages*.
GNU Emacs 24.4.1 (i686-pc-mingw32) of 2014-10-24 on LEG570. Hm that's old. Shall I try 2.25?

Dann eher Big Easy (ich kenne beide noch nicht).

**Comment by jorgenschaefer** [comment]
24.x should be fine. I have a very bad feeling about this.

What does `M-: (featurep 'make-network-process '(:nowait t))` return for you?

**Comment by zenon** [comment]
nil
Whithout the nowait, I get t. In case that's interesting to you.

**Comment by jorgenschaefer** [comment]
Ok. So that's the problem – your Emacs does not support non-blocking connects, which is rare (and apparently Windows-specific), and Circe has had a bug with that since 2.0.

**Comment by jorgenschaefer** [comment]
Could you try the above commit and see if that fixes things for you?

**Comment by zenon** [comment]
First the good news: Connect works!!! And SASL!

Well, the drawack is, I cannot join any channel.

/join #channelchannel 

gives

Error running event nil handler circe--irc-display-event: (wrong-type-argument processp nil) (args were (#<process chat.freenode.net> "JOIN" "nicnic!~nicnic@unaffiliated/nicnic" "#channelchannel" "Nicnic" "Nic Nic"))

New ticket?

**Comment by jorgenschaefer** [comment]
Correct way – I force-pushed (bad me) a quick fix shortly after making the first push, did you use that version? I forgot to return the process object at the end of the function.

**Comment by zenon** [comment]
Yes. I took the wrong version. Now it works. Thank you for your patience!

Und Du hast mail (gmail) :-)

**Comment by jorgenschaefer** [comment]
Yeeessss! Thank you for the patience, too. :-) This was a pretty long-standing bug, and it took me way too long to track that down.
