### ISSUE TITLE
widget-apply error upon expanding "Circe Channel Killed Confirmation" node via customize-group

### ISSUE THREAD

**Issue by dustinpaluch** [jorgenschaefer/circe#264]
Expericing 100% reproducability. Here's what I did:
`emacs -Q`, `(package-initialize) (require 'circe)`, M-x customize-group RET circe RET,  click the arrow next to "Circe Channel Killed Confirmation". I expect the node to open revealing the value of this variable and a STATE button, but instead, the node disappears entirely, and I get

    widget-apply: Symbol's function definition is void: nil

In the \*Messages* buffer. The backtrace I get from tdoe is ~2,000,000 characters long:
https://gist.github.com/dustinpaluch/00f8abd975bfa3a7fdae92e7381aff05

Circe 2.2 via melpa-stable
GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.30) of 2016-05-18

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! Good catch. Simple typo, but wow, what an unreadable error :-D

**Comment by dustinpaluch** [comment]
My pleasure! Thanks for the fix.
