### ISSUE TITLE
Advertisement in circe-default-quit-message

### ISSUE THREAD

**Issue by defanor** [jorgenschaefer/circe#272]
Though advertising software in quit messages is common among IRC
clients, it's quite spammy, and doesn't seem like a nice thing to do
by default.

Unless it is deemed important, perhaps an empty quit message should be
used by default. Random funny quit messages may also be nice.

**Comment by jorgenschaefer** [comment]
It is very important (and a humorous reference to Greek mythology). You can easily change the default if you don't like it. :-)
