### ISSUE TITLE
Circe fails silently when gnutls-cli is not present

### ISSUE THREAD

**Issue by aidalgol** [jorgenschaefer/circe#287]
While setting up Emacs (and Circe, of course) on a new system, I forgot to install `gnutls-cli`, so Circe failed to connect, but it did not give me any error; the server buffer just sat indefinitely with the initial `*** Connecting...` line.  I think Circe should detect this condition and give an appropriate error message to the user.

**Comment by DamienCassou** [comment]
I agree, I had the same problem.

**Comment by wasamasa** [comment]
I can reproduce this by changing the customizable so that the openssl command is called.  Perhaps the issue is within the specific invocation and that it doesn't create a usable subprocess?

**Comment by ckruse** [comment]
Same when things go wrong. GnuTLS is available and in path, but circe silently fails and I have no idea what's happening.

**Comment by fturco** [comment]
On Gentoo I had to rebuild the `net-libs/gnutls` package with the `tools` USE flag and restart Emacs.

**Comment by wasamasa** [comment]
Closed with https://github.com/jorgenschaefer/circe/issues/377
