### ISSUE TITLE
Is there a way to use SASL without having a separate section in .emacs?

### ISSUE THREAD

**Issue by computersarecool** [jorgenschaefer/circe#292]
Hi,

I started using circe because I wanted to have SASL support and I am really enjoying using it.  However, I would like to be able to type in my SASL-username each time rather than have to hard code it into my config file.

Is there a way to do this?

**Comment by wasamasa** [comment]
This is supported for passwords (by supplying a custom function), but doesn't appear to be for usernames.

**Comment by computersarecool** [comment]
Could you show me how it is supported?

**Comment by wasamasa** [comment]
You pass the function's symbol or a lambda.  I've added an example to the wiki: https://github.com/jorgenschaefer/circe/wiki/Configuration#safer-password-management

**Comment by computersarecool** [comment]
This works for me. Thanks
