### ISSUE TITLE
CTCP handler does not check for empty arguments

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/circe#296]
```
Error running event nil handler circe--irc-display-event: (wrong-type-argument stringp nil) (args were (#<process irc.freenode.net> "irc.ctcp.PING" "zooey!~zooey@gateway/tor-sasl/zooey" "forcer" nil))
```

**Comment by alphor** [comment]
Is this already fixed? there's a when clause on irc-handle-ctcp--ctcp-ping that should prevent this error.

**Comment by jorgenschaefer** [comment]
Running `(circe--irc-display-event (circe-server-process) "irc.ctcp.PING" "zooey!~zooey@gateway/tor-sasl/zooey" "forcer" nil)` in a server buffer still causes this error for me, so nope, not fixed yet.

**Comment by alphor** [comment]
More digging with edebug found it, text is set to nil [here](https://github.com/jorgenschaefer/circe/blob/master/circe.el#L2955) and it is passed to string-to-number which generates the error.

**Comment by alphor** [comment]
If you want I can write a test case and PR that solves the issue.

**Comment by jorgenschaefer** [comment]
That would be awesome! Thank you for your work :-)

**Comment by alphor** [comment]
Wait, I forgot to ask, would you want nil to be coerced to 0 in this case?

**Comment by jorgenschaefer** [comment]
Probably some descriptive text like in `circe-display-ctcp-ping`, I'd say?
