### ISSUE TITLE
Can't customize circe-server-max-reconnect-attempts to nil through customize UI

### ISSUE THREAD

**Issue by jlf** [jorgenschaefer/circe#302]
It's not clear how to configure Circe to continue reconnection attempts indefinitely through the customization UI.  Using values of "nil", "()", or "'()" in the text field results in 
```Debugger entered--Lisp error: (error "This field should contain an integer")``` 
and leaving the text field empty results in 
```Debugger entered--Lisp error: (error "Empty sexp -- use nil?")```

**Comment by jorgenschaefer** [comment]
I guess the patch by wasamasa fixed it? (Thanks, btw!)

**Comment by jlf** [comment]
Confirmed fixed, thanks again.
