### ISSUE TITLE
Custom keywords in circe-format-* options?

### ISSUE THREAD

**Issue by vyp** [jorgenschaefer/circe#309]
Would it be possible to use custom keywords for the `circe-format-*` options?

The only use case I have for this at the moment is that I want to set a maximum length for `{nick}` (for example in `circe-format-say`). To illustrate my idea better, I was thinking about being able to use a custom `lui-format` or something like the following somehow:

``` elisp
(let ((nick "averylongnickname")
      (maxlen 10))
  (when (> (length nick) maxlen)
    (setq nick (substring nick 0 maxlen)))
  (lui-format (concat "{nick:-" (number-to-string maxlen) "s}")
              :nick nick))
```

Does this make sense?

**Comment by jorgenschaefer** [comment]
Hello! Yes, this does make sense to some extent – `lui-format` simply uses Emacs' `format` underneath, so adding more functionality is quite a bit of work. But it supports functions instead of values, too. The following should do what you want, for example:

```Lisp
(defun nick-truncated (&rest args)
  (let ((nick (plist-get args :nick))
        (message (plist-get args :message))
        (maxlen 10))
    (when (> (length nick) maxlen)
      (setq nick (substring nick 0 maxlen)))
    (format "<%5s> %s" nick message)))

(setq circe-format-say 'nick-truncated)
```

**Comment by vyp** [comment]
Thanks a lot! I haven't had time to try this yet, but this should resolve my question once I confirm it works for me. However, you seem to have added this to a milestone, so I'm presuming you would want to keep this open anyway?

Also, some follow-up questions:

1. Why is it `:message` and not `:body` as the documentation for `circe-format-say` says? (And so, where can these argument names be found?)

2. Would it be possible to determine what format option the function is handling? For example, I'd like to configure more than just `circe-format-say` (e.g. `circe-format-action`, `circe-format-notice` etc), and so having separate functions for all of them would result in a lot of code duplication. (I'm assuming just having the argument list be something like `(option &rest args)` would not work?)

**Comment by jorgenschaefer** [comment]
No need to leave this open, I just keep tickets associated with releases :-)

As for the questions:

1. It's actually `:body`, I got it wrong.
2. You can have your functions call a common function to handle duplicated code :-)

**Comment by vyp** [comment]
> You can have your functions call a common function to handle duplicated code :-)

Oh right yeah, that works, thanks! But nicks aren't colorized anymore (and also if anyone mentions my nick, my nick is not colorized anymore, but *their nick* is colorized), it's not a big deal, but is there anyway to keep them colorized as well?

**Comment by jorgenschaefer** [comment]
> but is there anyway to keep them colorized as well?

Hm. Oh, right, there's some unobvious magic happening in the highlighter there … try using `(lui-format "<{nick:5s}> {body}" :nick nick :body body)` in the code above, with `nick` being the shortened version. Circe actually looks for the format specifiers from `lui-format` in the string output …

**Comment by vyp** [comment]
That works! Thanks again! :tada:
