### ISSUE TITLE
Tweaking IRC disconnect parameters on flaky networks

### ISSUE THREAD

**Issue by galderz** [jorgenschaefer/circe#319]
Hi,

Once certain wifi/lan networks, I'm seeing IRC disconnects happen very regularly. To the point that almost every time I check IRC I've been disconnected.

e.g.

    [read:errno=54 from nil]
    Disconnected
    ...

These networks seem to behave well otherwise WRT internet connection. Is there a way to tweak how quickly circe decides/checks for disconnects? e.g. possibility to tweak timeouts?

Cheers,
Galder

**Comment by jorgenschaefer** [comment]
Hm. Circe does not set any particular timeouts, this is just normal network connections done with Emacs.

Are you using openssl, gnutls, or Emacs directly for connection?

**Comment by galderz** [comment]
Hi, just use Emacs directly. Any ideas?

**Comment by jorgenschaefer** [comment]
Hm. I don't see anything in `make-network-process` that would affect this I'm afraid. :-(

**Comment by galderz** [comment]
Actually, I think I'm using openssl since I see:

    openssl s_client -connect irc.freenode.net 6697

Anything I could tweak there?

**Comment by jorgenschaefer** [comment]
Hm. Nothing I saw in `man s_client`, I'm afraid. You could try gnutls instead I guess, not sure that would solve anything.

**Comment by wasamasa** [comment]
Can you still reproduce this with this fix: https://github.com/jorgenschaefer/circe/issues/377 ?

**Comment by galderz** [comment]
No longer using circe.
