### ISSUE TITLE
circe & gitter

### ISSUE THREAD

**Issue by seblemaguer** [jorgenschaefer/circe#321]
Hello,

I try to make circe working with gitter. I used this configuration:

```elisp
 (setq circe-network-options
          '(
            ("gitter"
             :tls t
             :nick "seblemaguer"
             :sasl-password my-irc-password
             :server-buffer-name "⇄ gitter"
             :host"irc.gitter.im"
             :service "6667")
            ))
```

but so far no success.

**Comment by wasamasa** [comment]
This configuration will pass the symbol `my-irc-password` literally to Circe which is probably not what you want.  If you want a variable by that name with the password as value to be used, you must use backquote instead:

```elisp
(setq circe-network-options
      `(("gitter"
         :tls t
         :nick "seblemaguer"
         :sasl-password ,my-irc-password
         :server-buffer-name "⇄ gitter"
         :host"irc.gitter.im"
         :service "6667")))
```

**Comment by seblemaguer** [comment]
thanks a lot. `my-irc-password` is function. I used it to access to the authinfo which is storing my password and for the other networks. I tried to connect using the password directly indicated as a string it is not working. This is my log:

```
E: "conn.connected" 
C: CAP LS
C: NICK seblemaguer
C: USER slemaguer 8 * slemaguer
S: ERROR :You must authenticate, check: https://irc.gitter.im
E: "ERROR" nil "You must authenticate, check: https://irc.gitter.im"
S: - Peer has closed the GnuTLS connection
E: "-" nil "Peer" "has" "closed" "the" "GnuTLS" "connection"
E: "conn.disconnected" 
E: "conn.connected" 
C: CAP LS
C: NICK seblemaguer
C: USER slemaguer 8 * slemaguer
C: QUIT :Using Circe, the loveliest of all IRC clients
```

**Comment by wasamasa** [comment]
Hm, perhaps `:sasl-password` is the wrong key then.  Did you try `:pass` instead?

**Comment by seblemaguer** [comment]
perfect, that was it. Thanks a lot

**Comment by mcraveiro** [comment]
Hi

Many thanks for a great software package for emacs. I also have a problem setting up Circe for gitter. I tried following the code from @seblemaguer but sadly I'm not the best at emacs lisp :-) I tried to combine the wiki instructions with his tips and came up with:

```
(setq auth-sources '("~/.authinfo.gpg"))

(defun my-fetch-password (&rest params)
  (require 'auth-source)
  (let ((match (car (apply 'auth-source-search params))))
    (if match
        (let ((secret (plist-get match :secret)))
          (if (functionp secret)
              (funcall secret)
            secret))
      (error "Password not found for %S" params))))

(defun my-nickserv-password (server)
  (my-fetch-password :login "mcraveiro" :machine "irc.gitter.im"))

(setq circe-network-options
      `(("Gitter"
         :tls t
         :nick "mcraveiro"
         :pass my-nickserv-password
         :server-buffer-name "⇄ gitter"
         :host "irc.gitter.im"
         :service "6667")))
```

When I start circea and choose ```Gitter``` I don't seem to be connected:

```
*** Connecting...
*** No target for current buffer
>
 ```

I also replaced ```my-nickserv-password``` with the actual password to test it and it still does not connect. Also, I couldn't locate the logs that @seblemaguer posted above.

Any tips or ideas would be greatly appreciated.

Many thanks for your time

Marco

**Comment by wasamasa** [comment]
To obtain the above log, evaluate `(setq irc-debug-log t)` and look for a "IRC Protocol" buffer. For testing I'd recommend omitting the auth-source parts and just using the literal password.

**Comment by mcraveiro** [comment]
Hi @wasamasa,

Thanks very much for that. So using a literal password and with debug log I get:

```
E: "conn.failed" 
C: QUIT :Using Circe, the loveliest of all IRC clients
E: "conn.failed" 
```

**Comment by wasamasa** [comment]
Hm, this means it's an issue happening before the client has even a chance to establish a connection. Do you have `gnutls-cli` on PATH?

**Comment by mcraveiro** [comment]
ah interesting! well I installed the package as per wiki and then if I do:

```
$ which gnutls-cli
/usr/bin/gnutls-cli
```
That looks healthy...

**Comment by wasamasa** [comment]
Yeah, at this point you'd need to do manual testing by opening a connection to the server with `gnutls-cli` and looking for anything suspicious. Alternatively, try applying this hack before I do: https://github.com/jorgenschaefer/circe/issues/306#issuecomment-493236603
