### ISSUE TITLE
Add INFO node

### ISSUE THREAD

**Issue by jidanni** [jorgenschaefer/circe#329]
There is no .info file, just those of the "competitors",
```
$ dlocate rc.info
emacs25-common-non-dfsg: /usr/share/info/emacs-25/erc.info.gz
emacs25-common-non-dfsg: /usr/share/info/emacs-25/rcirc.info.gz
```
even after I did
```
# aptitude install elpa-circe
```

**Comment by wasamasa** [comment]
IIRC there used to be one, but it was dropped in favor of the Wiki.

**Comment by jidanni** [comment]
Even though one could say one is probably online when using the program,
one would still like to read-up on it offline, etc.

Anyway surely there is some script to convert wiki pages to INFO
pages...
Ah, "About pandoc
If you need to convert files from one markup format into another, pandoc is your swiss-army knife. "

**Comment by jorgenschaefer** [comment]
Texinfo is a terrible format to write documentation in. Info is a terrible format to read information from. The documentation we had was outdated and badly maintained. I don't see that Circe will have an info manual again, ever.

Shouldn't stop people who want to spend effort on this in writing one, but I'd hesitate adding it to this repository as it will most certainly be outdated soon enough again. The wiki is hard to update as is. But a separate package would work.

**Comment by jidanni** [comment]
pandoc --to=texinfo, --to=pdf ...
