### ISSUE TITLE
Compiling discussed after Connecting

### ISSUE THREAD

**Issue by jidanni** [jorgenschaefer/circe#330]
https://github.com/jorgenschaefer/circe/wiki/Manual has
1. Connecting to IRC
1. Compiling Circe <--- really doesn't belong at this place.
1. Concepts

**Comment by jorgenschaefer** [comment]
Why do you think so?

**Comment by jidanni** [comment]
OK first we connect, then we compile.

**Comment by jorgenschaefer** [comment]
Yup, that works. Please feel free to improve the manual, though! :-) Closing this issue, as it's not something we'll be working on.
