### ISSUE TITLE
message still stays in the minibuffer

### ISSUE THREAD

**Issue by jidanni** [jorgenschaefer/circe#331]
Start circe offline, it cannot connect, so go to the buffer and do C-x k
```
Really kill all buffers of this server? (if not, try `circe-reconnect') (y or n) y
```
but that message still stays there in the minibuffer!
(circe-version)"Circe 2.6"(emacs-version)"GNU Emacs 25.2.2...

**Comment by wasamasa** [comment]
Yes, that's the nature of the echo area (it's only called the minibuffer if you edit text in it), the displayed text stays there until replaced by another one or executing a command. This isn't a Circe bug at all, just standard Emacs behavior.

**Comment by jidanni** [comment]
Try this experiment,
```
$ emacs
C-x k
```
You will see the message
```
Kill buffer (default ...):
```
and when you answer "y", poof, buffer and message both gone!

That is the correct way.

**Comment by wasamasa** [comment]
I can't reproduce that here actually:

![](https://i.imgur.com/i4qe30j.png)

**Comment by jidanni** [comment]
```
# su - nobody #or just us another pristine account
No directory, logging in with HOME=/
nobody@jidanni6:/$ emacs -nw
C-x k
```

**Comment by jorgenschaefer** [comment]
Circe uses the built-in `y-or-n-p` method. If you feel this method should clean out the echo area after reading the response, please file a bug report with Emacs itself.

**Comment by jidanni** [comment]
OK, made https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30587 .
