### ISSUE TITLE
WHO messages

### ISSUE THREAD

**Issue by rphillips** [jorgenschaefer/circe#337]
I am connecting Circe through ZNC, and every 10-15 seconds I get a spam of 354 (who messages) into any channel buffer that is open. They should be filtered to the server buffer, or suppressed. I am not sure who is querying for the WHO information.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. You can filter them by using `(circe-set-display-handler "354" 'circe-display-ignore)` – usually, typing `/WHO` should result in the list of users in your channel, not in the server buffer. I would suggest you try and find out who is sending the command, though!

**Comment by rphillips** [comment]
Thanks! That command certainly suppresses the message.I'll continue to dive into to see who is sending the message.
