### ISSUE TITLE
Cannot filter quit messages

### ISSUE THREAD

**Issue by matthew-piziak** [jorgenschaefer/circe#341]
I have `(circe-set-display-handler "QUIT" (lambda (&rest ignored) nil))` in my config, but I still see Quit messages in Circe. Have I misread the documentation?

`Circe 2.10`

`GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.28) of 2018-08-06`

**Comment by wasamasa** [comment]
There's two handled events here, `QUIT` and `channel.quit`. Judging from the sources `channel.quit` is the more important one, with the `QUIT` one being useful for quits in queries.

**Comment by matthew-piziak** [comment]
This works. Thank you! Maybe it could be added to the wiki?

**Comment by wasamasa** [comment]
Sure. The point of a wiki is that anyone can add things to it. I would if I knew the convention for the event naming, telling people to study sources feels kind of wrong...
