### ISSUE TITLE
Automatically track :channels even if unvisited

### ISSUE THREAD

**Issue by matthew-piziak** [jorgenschaefer/circe#342]
All channels set in `:channels` should be added to `tracking-buffers` when they have activity, even if the buffer was never visited by the user.

**Comment by jorgenschaefer** [comment]
Interesting. Why?

**Comment by matthew-piziak** [comment]
Huh. I guess I thought it made sense to have channels be tracked when they are joined, not when they are visited, but maybe that's not a universal use case? I usually like to launch Circe, and then read new messages posted to my joined channels when they come in.

**Comment by jorgenschaefer** [comment]
But if you join them and nothing happens there, there's nothing to read. If something happens, Circe adds them to the tracked buffers. I still do not understand this use case?

**Comment by matthew-piziak** [comment]
Oh, I'm not observing that second part. When something happens, Circe does not add them to the tracked buffers. I have to visit them first, and _then_ if new messages come in I get tracking. But if that's not expected then I should look into my configuration more.

**Comment by matthew-piziak** [comment]
After upgrading my packages I cannot reproduce. Sorry about that!
