### ISSUE TITLE
How do I show my nick instead of >>

### ISSUE THREAD

**Issue by gregf** [jorgenschaefer/circe#347]
Hi,

I"m very new to lisp and i'm wondering how I could change the display to show my nickname instead of just >> when I talk in a irc channel? Sorry if this is to much to ask in the issue tracker. Thank you!

**Comment by wasamasa** [comment]
The easiest solution is to customize `circe-prompt-string` to something like "<gregf> ". The issue with this is that you're hardcoding your nickname, if you're ever using multiple networks with different nicknames, it wouldn't use the correct nickname on each network. For such a usecase you'd need to do something more involved, like the following untested snippet:

```elisp
(defun my-circe-nick-prompt ()
  (lui-set-prompt (concat (circe-nick) " ")))

(add-hook 'circe-mode-hook 'my-circe-nick-prompt)
```

**Comment by jorgenschaefer** [comment]
wasamasa's solution changes the prompt. If you are talking about the lines you say in the channel, you can just do `(setq circe-format-self-say "<{nick}> {body}")`.

**Comment by gregf** [comment]
Both of those are things I would like to be able to do. Thank you both very much!
