### ISSUE TITLE
backward-kill-word should be limited by current line.

### ISSUE THREAD

**Issue by sarg** [jorgenschaefer/circe#349]
When I type non-alphabetic symbol at the beginning of input line I can't delete it with `backward-kill-word`.

To reproduce: enter `@` then `C-w`.
```
> @<C-w>
```
Get error: `kill-region: Text is read-only: #<buffer irc.freenode.net:6667>`

**Comment by wasamasa** [comment]
The only special thing Circe does here is providing `lui-kill-to-beginning-of-line`, bound to `C-c C-u` by default. It behaves correctly in this situation, so consider using that instead.

**Comment by sarg** [comment]
With `(setq circe-prompt-string (concat  "> " (propertize "!aa!" 'invisible t)))` `C-w` behaves correctly. Consider making it a default.

**Comment by wasamasa** [comment]
That's just bonkers. Consider writing a custom kill command that respects the beginning of the line.
