### ISSUE TITLE
Bad link in the docstring of irc-send-AUTHENTICATE

### ISSUE THREAD

**Issue by edrx** [jorgenschaefer/circe#354]
The current docstring for irc-send-AUTHENTICATE points to this URL:
https://github.com/atheme/charybdis/blob/master/doc/sasl.txt
that gives a 404... I think that it should be changed to:
https://github.com/charybdis-ircd/charybdis/blob/master/doc/features/sasl.txt

**Comment by wasamasa** [comment]
Thanks! That being said, the document points to http://ircv3.atheme.org/extensions/sasl-3.1 as authoritative source which naturally doesn't resolve. Have you per chance done some more research on what the authoritative source is?
