### ISSUE TITLE
SASL External

### ISSUE THREAD

**Issue by travankor** [jorgenschaefer/circe#375]
Can you add support for SASL external (rfc 4422)?

Refs:
https://tools.ietf.org/html/rfc4422
https://ircv3.net/specs/extensions/sasl-3.1

**Comment by wasamasa** [comment]
How is this an improvement over SASL with PLAIN over a TLS connection?

**Comment by travankor** [comment]
SASL External hard fails without TLS. Additionally, you need SASL External to access some networks.

Additionally, it's part of the IRCv3 standard and you can use znc certauth.

**Comment by wasamasa** [comment]
This will be closed by #386
