### ISSUE TITLE
[Question] how do I disable tracking from using the modeline?

### ISSUE THREAD

**Issue by ag91** [jorgenschaefer/circe#378]
Hi, thanks for tracking.el it is nice to jump from buffer to buffer so easily.
I am using https://github.com/yuya373/emacs-slack that uses your tracking.el library.
I would like my modeline to stay clean of alerts, and I hoped that setting 
```
(setq tracking-max-mode-line-entries 0)
```
would do the trick. However that still leaves a single add an entry to the modeline, because the loop in `tracking-status` does not check for the 0 value.
I ended up disabling it with a hack:
```
(defun tracking-status () nil)
```
What influenced your design to have always at least an entry in the modeline? Would it make sense to change it and would you like a PR?

**Comment by wasamasa** [comment]
Why not `(tracking-mode -1)`?

**Comment by wasamasa** [comment]
I can't speak for the author's design decisions, but wouldn't be surprised if they never tested it for the case of zero.  Irregardless of that I'd review a PR fixing this oversight.
