### ISSUE TITLE
add sasl authentication

### ISSUE THREAD

**Issue by zabbal** [jorgenschaefer/circe#81]
Emacs have built-in sasl library and freenode supports sasl authentication (mandates it in some cases in fact). It would be great to use those features. Especially considering that it might save user from dealing with nickserv authentication for example.

**Comment by wasamasa** [comment]
@Earnestly pointed me to [an useful Gist](https://gist.github.com/grawity/8389307) that explains the protocol details in a bit more detail.

**Comment by jorgenschaefer** [comment]
Small update here: The new irc.el code actually supports SASL authentication, but the current bridging code does not support passing the relevant options yet. This should be a feature of Circe 1.7, though.
