### ISSUE TITLE
Triple-clicking a line doesn't select it in Emacs 24.4

### ISSUE THREAD

**Issue by wasamasa** [jorgenschaefer/circe#98]
Triple-clicking is a mechanism found in numerous applications to select one visual line of text, including Emacs. In Emacs 24.3 triple-clicking does select a line of text in a Circe buffer, in Emacs 24.4 the line is flashing up shortly, then gets deselected. My research so far hasn't found much to operate on except the (intangible?) text properties which are a bit unusual, perhaps something upstream changed regarding them and clicks.

**Comment by jorgenschaefer** [comment]
Any update on this? Did you manage to create a line that exhibits this behavior outside of Circe yet (good for testing purposes)?

**Comment by wasamasa** [comment]
No, I've only tried disabling `lui` customizations without any success. Thanks for the idea, that way I will hopefully obtain a minimal example.

**Comment by jorgenschaefer** [comment]
Reported upstream: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=20260
